### ISSUE TITLE
DevourX.dll does not appear to be working after the latest update

### ISSUE THREAD

**Issue by cavinatto** [jadis0x/DevourX#2]
Firstly, I want to thank you for providing the DevourX.dll for free. It is a efficient and easy-to-use tool. However after the latest DEVOUR update (v5.0.21), DevourX.dll is no longer working, whenever I try to inject it using Process Hacker, the game crashes immediately. I'm currently using Windows 10.

**Name of the failing application:** DEVOUR.exe
**Version:** 2021.3.36.1605
**Module that failed:** UnityPlayer.dll
**Exception code:** 0xc0000005
**Fault offset:** 0x00000000000925f3
**Process ID:** 0xe30
**Path of the failing application:** C:\Program Files (x86)\Steam\steamapps\common\Devour\DEVOUR.exe
**Path of the module:** C:\Program Files (x86)\Steam\steamapps\common\Devour\UnityPlayer.dll

**Comment by jadis0x** [comment]
fixed
